### ISSUE TITLE
Current Podfile fails in `pod install`

### ISSUE THREAD

**Issue by BrianBatchelder** [sobri909/ArcMini#101]
[This change](https://github.com/sobri909/ArcMini/commit/0e588be13b43decf30c688091f0ad673bdaabf5a) broke `pod install`. The first target needs an `end`. Even with that, the way it is currently configured will fail as follows:
```
[!] There are multiple dependencies with different sources for `LocoKit` in `Podfile`:

- LocoKit (from `https://github.com/sobri909/LocoKit.git`, branch `develop`)
- LocoKit (from `~/Projects/LocoKit`)`
```

If both targets use the same pods, you might want to use an [`abstract_target`](https://guides.cocoapods.org/syntax/podfile.html#abstract_target) instead, e.g.

```ruby
abstract_target 'All' do
  # Arc Mini development follows the LocoKit develop branch, not the stable releases
  pod 'LocoKit', :git => 'https://github.com/sobri909/LocoKit.git', :branch => 'develop'
  pod 'LocoKitCore', :git => 'https://github.com/sobri909/LocoKit.git', :branch => 'develop'

  # uncomment this line if you're using a local copy of LocoKit 
  # pod 'LocoKit', :path => '~/Projects/LocoKit'

  target 'Arc Mini'
  target 'RecordersWidgetExtension'
end

**Comment by sobri909** [comment]
Oops! Sorry about that. I have local changes to the Podfile for local development, which aren't supposed to be checked in. That's one of them. Will revert/fix. Thanks for the heads up!

Also yeah, agree an 'All' target seems more sensible for now too. With heavier use of CocoaPods in the past there were more cases where different targets had different needs, but with SwiftPM mostly taking over these days, that need is gone.

**Comment by sobri909** [comment]
Aside: This reminds me I need to get #80 and #62 done, so that Arc Mini can ditch the CocoaPods dependency.

**Comment by BrianBatchelder** [comment]
No CocoaPods! It's like some kind of dream... ;-)

Actually, CocoaPods has helped me out a lot over the years. It's just time for something new.
