### ISSUE TITLE
Recorders widget isn't showing dots on iOS 15

### ISSUE THREAD

**Issue by sobri909** [sobri909/ArcMini#126]

**Comment by thoughtgap** [comment]
Not an iOS 15 issue, dots weren't there prior

**Comment by sobri909** [comment]
Ah ok, thanks! I guess I haven't checked on that widget in quite a while. Oops 😏

**Comment by sobri909** [comment]
K, I'm gonna make the current item widget do all the same stuff, and ditch this widget.
