### ISSUE TITLE
Arc Mini crashes on launch, Arc seems to be fine

### ISSUE THREAD

**Issue by blackketter** [sobri909/ArcMini#143]
I have Arc Mini and Arc installed for 3 days from the App Store and really like both.  

Arc seems to be working fine, but Arc Mini crashes on launch.  

Tried restarting the phone, didn't help.  Anything I can do apart from deleting and reinstalling (and losing my data) to diagnose the issue?

**Comment by sobri909** [comment]
If you delete Arc Mini you won't lose your data, as long as Arc App is still installed. Because they share an "App Group" container, the data in that container remains until both apps are deleted. 

Was Mini crashing on launch as soon as you first installed it? Or only after a few days? I'm not aware of any crashes in Mini at the moment, but I'll have a poke around in the crash logs in Xcode to see if anything stands out.

**Comment by blackketter** [comment]
This was after a couple of days.  I tried relaunching it a few more times.  Once it took a few seconds to crash then it stopped crashing altogether.

**Comment by sobri909** [comment]
I wonder if perhaps there's some timeline data in the current day that's upsetting Mini somehow, but isn't upsetting Arc App.

I've got no guesses what that data might be. (I mean, really it shouldn't be possible, so if I knew I'd have already fixed it 😂). But if that is the cause, then it means it will self correct within hopefully a day or two, once that data isn't visible in the current day nor the previous day (which is pre-fetched, to make swiping back a day in the UI more smooth).

**Comment by sobri909** [comment]
Actually my first guess was something like the installed Arc Mini version being out of date, such that it's missing a new ActivityType that was added to both Arc App and Arc Mini recently. Conceivably that could cause a crash.

Though it hasn't ever caused crashes before, that I'm aware of. LocoKit should cope gracefully with unknown activity types in the database. But it's the most plausible guess I've got so far.

So it might be worth checkin the App Store to make sure Mini is definitely updated to the latest version. A long shot, given you installed them only a few days ago. But yeah, my best/only guess so far.

**Comment by blackketter** [comment]
Yep, they both are the latest versions and I see no updates in my history...

**Comment by sobri909** [comment]
I just started getting a repeating crash in Mini yesterday. So presumably whatever it is has hit my phone too now. Hopefully can debug it quickly now!

**Comment by blackketter** [comment]
Started happening again today with Arc mini. Reinstalled Arc and it’s working fine.

**Comment by blackketter** [comment]
I should have been clearer: I had previously uninstalled Arc (not mini) and reinstalled it today.  It works fine.

Arc Mini is still crashing, but I noticed that as the day went on Arc didn't crash when I launched it.  BUT it does crash when I scroll down to the beginning of the day. 

 So I suspect there's some data from earlier today that's triggering the crash that doesn't get parsed until I scroll to it.

**Comment by sobri909** [comment]
Thanks! That sounds like it confirms (or at least reenforces) my hunch about it being some data that Arc App is happy with but Mini isn't.

I don't see any convincingly relevant crashes showing up in Xcode's downloaded crash details yet... But it's got to be in there. There's at least two of us seeing these crashes now. Hmm.

**Comment by blackketter** [comment]
I can reliably crash Arc Mini by going to yesterday (2023-09-01) and scrolling to the bottom.  Is there any export or logs that would help you?

**Comment by sobri909** [comment]
Yeah you could have a poke around in the JSON of Arc App's iCloud Drive backups, if you've got those toggled on in Arc App's settings.

Though I think even with my trained eye I'd struggle to spot clues in the JSON. I wouldn't know what to look for. If I did, I'd already have a speculative bug fix ready. Heh.

There's one crash showing up in Xcode's organiser that looks like it could be it, but only by elimination of the other two definitely not being it (a crash in the widget, and a crash during a scheduled background processing task). But it's painfully ambiguous.

Though... I do see one potential lead in a thread that wasn't the crashing one, but does look like it was still in-flight. Something to do with Date decoding from the database. Hmm.

**Comment by blackketter** [comment]
I can't reproduce this anymore, so I'll close it...
